version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/carauction
      - JWT_SECRET=your_jwt_secret
      - NODE_ENV=production
      - CORS_ORIGIN=http://161.35.193.132
    depends_on:
      - mongo
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M

  admin-dashboard:
    build: ./admin-dashboard
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://161.35.193.132:3000
    depends_on:
      - backend
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
      - admin-dashboard
    restart: always
    deploy:
      resources:
        limits:
          memory: 128M

volumes:
  mongodb_data: 